services:
  supernode:
    container_name: n3n-supernode
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "7777:7777"
      - "7777:7777/udp"
    volumes:
      - ./config:/etc/n3n:ro

    command: [ "n3n-supernode", "start" ]
